---
#
# Quick playbook to pull and build ffmpeg with several codecs.
# Based on: https://trac.ffmpeg.org/wiki/UbuntuCompilationGuide
# With minor tweaks.
#
# Ozzy Johnson - 2014.09.18
#

- hosts: local
  vars:
    source_dir: "/usr/local/src"
    lib_dir: "/usr/local/lib"
    bin_dir: "/usr/local/bin"
    cpus: "-j5"
    

  roles:
  
   - { role: dorftv.ffmpeg }
